# Github Unmodifiable Settings
safe: true
lsi: false
source: .
markdown: kramdown
highlighter: rouge
# github: [Repository metadata]

# SEO Settings
title: Mark Monteiro
description: Mark Monteiro is a software engineer and web developer. This is his personal website and portfolio.
url: https://markmonteiro.info
logo: /favicon-194x194.png

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true

# Exclude certain files/directories from processing.
# By default, dotfiles and The following items will not be processed.
# "Gemfile"
# "Gemfile.lock"
# "node_modules"
# "vendor/bundle/"
# "vendor/cache/"
# "vendor/gems/"
# "vendor/ruby/"
exclude:
  - LICENSE
  - README.md
  - Rakefile
  - package.json
  - package-lock.json
  
collections:
  - projects
  - experiences

sass:
  implementation: sass-embedded
  style: :compressed

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-autoprefixer
